version: "3.8"

services:
  jenkins-docker:
    image: jenkins-docker
    container_name: jenkins-docker
    restart: always
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 50000:50000
